#define _CRT_SECURE_NO_WARNINGS 1
#include <stdio.h>
#include <stdlib.h>

void write_rom_to_js(FILE* out, const char* name, const char* filepath) {
    FILE* in = fopen(filepath, "rb");
    if (!in) {
        printf("Warning: Could not open ROM file %s\n", filepath);
        return;
    }

    fprintf(out, "  %s: new Uint8Array([\n    ", name);

    int byte;
    int count = 0;
    while ((byte = fgetc(in)) != EOF) {
        fprintf(out, "0x%02X, ", byte);
        count++;
        if (count % 16 == 0) {
            fprintf(out, "\n    ");
        }
    }
    
    // Remove last comma if needed, but JS allows trailing commas
    fprintf(out, "\n  ]),\n");
    fclose(in);
    printf("Successfully converted %s (%d bytes)\n", filepath, count);
}

int main() {
    FILE* out = fopen("roms.js", "w");
    if (!out) {
        printf("Error: Could not create roms.js\n");
        return 1;
    }

    fprintf(out, "// Preloaded Chip-8 ROMs generated by bin2js.c\n");
    fprintf(out, "const PRELOADED_ROMS = {\n");

    write_rom_to_js(out, "ibm", "IBM_Logo.ch8");
    write_rom_to_js(out, "maze", "Maze.ch8");
    write_rom_to_js(out, "pong", "Pong.ch8");

    fprintf(out, "};\n");
    fclose(out);
    return 0;
}
